# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('is_favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('poster', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ragnal.City'),
        ),
    ]
