# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnal', '0002_auto_20170624_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='poster',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
