# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnal', '0003_site_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='poster',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
