# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnal', '0004_auto_20170624_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area',
            field=models.CharField(max_length=150),
        ),
    ]
