# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 12:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170815_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bill',
            field=models.IntegerField(),
        ),
    ]
