# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170819_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
